{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Coverage reporting using the Cython plugin does not work for the 5.x series of coverage.py. For example, attempting to run coverage tests on [raysect](https://github.com/raysect/source) produces errors:\r\n```bash\r\npython setup.py build_ext -j4 --inplace --line-profile\r\ncoverage run -m unittest discover\r\n```\r\nOutput:\r\n```\r\n...................................................................................................................................................................................................................................................................................................................................................................................................................................................\r\n----------------------------------------------------------------------\r\nRan 435 tests in 2.122s\r\n\r\nOK\r\nCan't add file tracer data for unmeasured file '/home/jlovell/FUN/cherab/raysect/raysect/core/math/_vec3.pxd'\r\n```\r\n\r\nAttempting to produce HTML output also results in an error:\r\n```bash\r\ncoverage html\r\n```\r\n\r\nOutput:\r\n```\r\nCouldn't parse '/home/jlovell/FUN/cherab/raysect/raysect/core/acceleration/accelerator.pyx' as Python source: 'invalid syntax' at line 32\r\n```\r\n\r\nUsing coverage.py 4.5 on the same set of build files results in no errors reported about pyx files, and the HTML output is produced successfully.",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "Thanks for the report. Could be some change in the plugin API. Any investigation welcome.",
            "created_at": "2020-04-14T18:08:21Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-613595569",
            "id": 613595569,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "MDEyOklzc3VlQ29tbWVudDYxMzU5NTU2OQ==",
            "updated_at": "2020-04-14T18:08:21Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/613595569",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "I ran into a similar issue, but with different exceptions being raised...\r\n\r\nOutput from [this build](https://github.com/nocarryr/cython-sounddevice/runs/583882321) shows an exception raised when trying to add a `FileTracer` for a .pxd\r\n\r\nNo issues after [constraining coverage.py to 4.5.x](https://github.com/nocarryr/cython-sounddevice/runs/586143014) and it seems there are a LOT of changes:\r\nhttps://coverage.readthedocs.io/en/coverage-5.1/whatsnew5x.html\r\n\r\n<details>\r\n<summary>Log output from py.test</summary>\r\n<pre>\r\n Traceback (most recent call last):\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/main.py\", line 191, in wrap_session\r\n     session.exitstatus = doit(config, session) or 0\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/_pytest/main.py\", line 247, in _main\r\n     config.hook.pytest_runtestloop(session=session)\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/hooks.py\", line 286, in __call__\r\n     return self._hookexec(self, self.get_hookimpls(), kwargs)\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py\", line 93, in _hookexec\r\n     return self._inner_hookexec(hook, methods, kwargs)\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/manager.py\", line 87, in <lambda>\r\n     firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pluggy/callers.py\", line 203, in _multicall\r\n     gen.send(outcome)\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytest_cov/plugin.py\", line 254, in pytest_runtestloop\r\n     self.cov_controller.finish()\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pytest_cov/engine.py\", line 197, in finish\r\n     self.cov.stop()\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/control.py\", line 649, in save\r\n     data = self.get_data()\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/control.py\", line 703, in get_data\r\n     if self._collector and self._collector.flush_data():\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/collector.py\", line 426, in flush_data\r\n     self.covdata.add_file_tracers(self.mapped_file_dict(self.file_tracers))\r\n   File \"/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/coverage/sqldata.py\", line 516, in add_file_tracers\r\n     \"Can't add file tracer data for unmeasured file '%s'\" % (filename,)\r\n coverage.misc.CoverageException: Can't add file tracer data for unmeasured file '/home/travis/build/nocarryr/cython-sounddevice/cysounddevice/devices.pxd'\r\n</pre>\r\n</details>\r\n",
            "created_at": "2020-04-14T20:43:02Z",
            "html_url": "https://github.com/cython/cython/issues/3515#issuecomment-613671329",
            "id": 613671329,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/3515",
            "node_id": "MDEyOklzc3VlQ29tbWVudDYxMzY3MTMyOQ==",
            "updated_at": "2020-04-14T20:43:02Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/613671329",
            "user": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/1625941?v=4",
                "events_url": "https://api.github.com/users/nocarryr/events{/privacy}",
                "followers_url": "https://api.github.com/users/nocarryr/followers",
                "following_url": "https://api.github.com/users/nocarryr/following{/other_user}",
                "gists_url": "https://api.github.com/users/nocarryr/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/nocarryr",
                "id": 1625941,
                "login": "nocarryr",
                "node_id": "MDQ6VXNlcjE2MjU5NDE=",
                "organizations_url": "https://api.github.com/users/nocarryr/orgs",
                "received_events_url": "https://api.github.com/users/nocarryr/received_events",
                "repos_url": "https://api.github.com/users/nocarryr/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/nocarryr/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/nocarryr/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/nocarryr"
            }
        }
    ],
    "comments": 2,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/3515/comments",
    "created_at": "2020-04-14T17:16:31Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2020-04-14T18:07:36Z",
            "event": "labeled",
            "id": 3232295467,
            "label": {
                "color": "444444",
                "name": "defect"
            },
            "node_id": "MDEyOkxhYmVsZWRFdmVudDMyMzIyOTU0Njc=",
            "url": "https://api.github.com/repos/cython/cython/issues/events/3232295467"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2020-04-14T18:07:36Z",
            "event": "labeled",
            "id": 3232295468,
            "label": {
                "color": "444444",
                "name": "Tools"
            },
            "node_id": "MDEyOkxhYmVsZWRFdmVudDMyMzIyOTU0Njg=",
            "url": "https://api.github.com/repos/cython/cython/issues/events/3232295468"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/3515/events",
    "html_url": "https://github.com/cython/cython/issues/3515",
    "id": 599729428,
    "labels": [
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425563280,
            "name": "Tools",
            "node_id": "MDU6TGFiZWw0MjU1NjMyODA=",
            "url": "https://api.github.com/repos/cython/cython/labels/Tools"
        },
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425553654,
            "name": "defect",
            "node_id": "MDU6TGFiZWw0MjU1NTM2NTQ=",
            "url": "https://api.github.com/repos/cython/cython/labels/defect"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/3515/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU1OTk3Mjk0Mjg=",
    "number": 3515,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "Coverage plugin broken with coverage.py 5.x",
    "updated_at": "2020-04-14T20:43:03Z",
    "url": "https://api.github.com/repos/cython/cython/issues/3515",
    "user": {
        "avatar_url": "https://avatars1.githubusercontent.com/u/4849151?v=4",
        "events_url": "https://api.github.com/users/jacklovell/events{/privacy}",
        "followers_url": "https://api.github.com/users/jacklovell/followers",
        "following_url": "https://api.github.com/users/jacklovell/following{/other_user}",
        "gists_url": "https://api.github.com/users/jacklovell/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/jacklovell",
        "id": 4849151,
        "login": "jacklovell",
        "node_id": "MDQ6VXNlcjQ4NDkxNTE=",
        "organizations_url": "https://api.github.com/users/jacklovell/orgs",
        "received_events_url": "https://api.github.com/users/jacklovell/received_events",
        "repos_url": "https://api.github.com/users/jacklovell/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/jacklovell/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jacklovell/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/jacklovell"
    }
}