{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "Follow-up of #4046.\r\n\r\n(*) Enum formatting:\r\n\r\n```\r\nFAIL: cpdef_enums ()\r\nDoctest: cpdef_enums\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/home/vstinner/python/master/Lib/doctest.py\", line 2205, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for cpdef_enums\r\n  File \"/home/vstinner/dev/cython/TEST_TMP/run/c/cpdef_enums/cpdef_enums.cpython-310d-x86_64-linux-gnu.so\", line 1, in cpdef_enums\r\n\r\n----------------------------------------------------------------------\r\nFile \"/home/vstinner/dev/cython/TEST_TMP/run/c/cpdef_enums/cpdef_enums.cpython-310d-x86_64-linux-gnu.so\", line 39, in cpdef_enums\r\nFailed example:\r\n    str(PyxEnum.TWO)\r\nExpected:\r\n    'PyxEnum.TWO'\r\nGot:\r\n    'TWO'\r\n\r\n======================================================================\r\nFAIL: test_formatting_with_enum (test_unicode.UnicodeTest)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"tests/run/test_unicode.pyx\", line 1473, in test_unicode.UnicodeTest.test_formatting_with_enum (test_unicode.c:112176)\r\n    self.assertEqual(\"%s, %s\" % (Str.ABC, Str.ABC),\r\nAssertionError: 'ABC, ABC' != 'Str.ABC, Str.ABC'\r\n- ABC, ABC\r\n+ Str.ABC, Str.ABC\r\n```\r\n\r\n(*) optimised_pow2_inplace:\r\n\r\n```\r\nFAIL: optimised_pow2_inplace (powop)\r\nDoctest: powop.optimised_pow2_inplace\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/home/vstinner/python/master/Lib/doctest.py\", line 2205, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for powop.optimised_pow2_inplace\r\n  File \"/home/vstinner/dev/cython/TEST_TMP/run/c/powop/powop.cpython-310d-x86_64-linux-gnu.so\", line unknown line number, in optimised_pow2_inplace\r\n\r\n----------------------------------------------------------------------\r\nFile \"/home/vstinner/dev/cython/TEST_TMP/run/c/powop/powop.cpython-310d-x86_64-linux-gnu.so\", line ?, in powop.optimised_pow2_inplace\r\nFailed example:\r\n    optimised_pow2_inplace('test')\r\nExpected:\r\n    Traceback (most recent call last):\r\n    TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'str'\r\nGot:\r\n    Traceback (most recent call last):\r\n      File \"/home/vstinner/python/master/Lib/doctest.py\", line 1337, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest powop.optimised_pow2_inplace[9]>\", line 1, in <module>\r\n        optimised_pow2_inplace('test')\r\n      File \"tests/run/powop.pyx\", line 161, in powop.optimised_pow2_inplace (powop.c:2990)\r\n        x **= n\r\n    TypeError: unsupported operand type(s) for **=: 'int' and 'str'\r\n```\r\n\r\n(*) test_embed:\r\n\r\n```\r\nFAIL: test_embed (__main__.EmbedTest)\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/home/vstinner/dev/cython/runtests.py\", line 1797, in test_embed\r\n    self.assertEqual(0, os.system(\r\nAssertionError: 0 != 512\r\n```",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "There are also many gdb failures like \"FAIL: test_updown (Cython.Debugger.Tests.test_libcython_in_gdb.TestUpDown)\" but I prefer to ignore them for now (use a different issue for gdb). I don't know if these failures are specific to Python 3.10.",
            "created_at": "2021-04-07T12:53:45Z",
            "html_url": "https://github.com/cython/cython/issues/4100#issuecomment-814889502",
            "id": 814889502,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4100",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgxNDg4OTUwMg==",
            "performed_via_github_app": null,
            "updated_at": "2021-04-07T12:53:45Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/814889502",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/194129?v=4",
                "events_url": "https://api.github.com/users/vstinner/events{/privacy}",
                "followers_url": "https://api.github.com/users/vstinner/followers",
                "following_url": "https://api.github.com/users/vstinner/following{/other_user}",
                "gists_url": "https://api.github.com/users/vstinner/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/vstinner",
                "id": 194129,
                "login": "vstinner",
                "node_id": "MDQ6VXNlcjE5NDEyOQ==",
                "organizations_url": "https://api.github.com/users/vstinner/orgs",
                "received_events_url": "https://api.github.com/users/vstinner/received_events",
                "repos_url": "https://api.github.com/users/vstinner/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/vstinner/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/vstinner/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/vstinner"
            }
        },
        {
            "author_association": "NONE",
            "body": "Enum related changes were made in https://github.com/python/cpython/pull/22392",
            "created_at": "2021-04-07T13:34:42Z",
            "html_url": "https://github.com/cython/cython/issues/4100#issuecomment-814918890",
            "id": 814918890,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4100",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgxNDkxODg5MA==",
            "performed_via_github_app": null,
            "updated_at": "2021-04-07T13:34:42Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/814918890",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/3972343?v=4",
                "events_url": "https://api.github.com/users/tirkarthi/events{/privacy}",
                "followers_url": "https://api.github.com/users/tirkarthi/followers",
                "following_url": "https://api.github.com/users/tirkarthi/following{/other_user}",
                "gists_url": "https://api.github.com/users/tirkarthi/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/tirkarthi",
                "id": 3972343,
                "login": "tirkarthi",
                "node_id": "MDQ6VXNlcjM5NzIzNDM=",
                "organizations_url": "https://api.github.com/users/tirkarthi/orgs",
                "received_events_url": "https://api.github.com/users/tirkarthi/received_events",
                "repos_url": "https://api.github.com/users/tirkarthi/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/tirkarthi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/tirkarthi/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/tirkarthi"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Enum formatting: I created https://github.com/cython/cython/pull/4101 to fix it.",
            "created_at": "2021-04-07T13:42:46Z",
            "html_url": "https://github.com/cython/cython/issues/4100#issuecomment-814924651",
            "id": 814924651,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4100",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgxNDkyNDY1MQ==",
            "performed_via_github_app": null,
            "updated_at": "2021-04-07T13:42:46Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/814924651",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/194129?v=4",
                "events_url": "https://api.github.com/users/vstinner/events{/privacy}",
                "followers_url": "https://api.github.com/users/vstinner/followers",
                "following_url": "https://api.github.com/users/vstinner/following{/other_user}",
                "gists_url": "https://api.github.com/users/vstinner/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/vstinner",
                "id": 194129,
                "login": "vstinner",
                "node_id": "MDQ6VXNlcjE5NDEyOQ==",
                "organizations_url": "https://api.github.com/users/vstinner/orgs",
                "received_events_url": "https://api.github.com/users/vstinner/received_events",
                "repos_url": "https://api.github.com/users/vstinner/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/vstinner/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/vstinner/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/vstinner"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "> Enum related changes were made in python/cpython#22392\r\n\r\nRight. It's a deliberate change: https://docs.python.org/dev/whatsnew/3.10.html#enum",
            "created_at": "2021-04-07T13:43:30Z",
            "html_url": "https://github.com/cython/cython/issues/4100#issuecomment-814925232",
            "id": 814925232,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4100",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgxNDkyNTIzMg==",
            "performed_via_github_app": null,
            "updated_at": "2021-04-07T13:43:30Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/814925232",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/194129?v=4",
                "events_url": "https://api.github.com/users/vstinner/events{/privacy}",
                "followers_url": "https://api.github.com/users/vstinner/followers",
                "following_url": "https://api.github.com/users/vstinner/following{/other_user}",
                "gists_url": "https://api.github.com/users/vstinner/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/vstinner",
                "id": 194129,
                "login": "vstinner",
                "node_id": "MDQ6VXNlcjE5NDEyOQ==",
                "organizations_url": "https://api.github.com/users/vstinner/orgs",
                "received_events_url": "https://api.github.com/users/vstinner/received_events",
                "repos_url": "https://api.github.com/users/vstinner/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/vstinner/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/vstinner/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/vstinner"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "(*) optimised_pow2_inplace: I wrote https://github.com/cython/cython/pull/4103 to fix the test (updated, my PR #4102 didn't work).",
            "created_at": "2021-04-07T14:15:19Z",
            "html_url": "https://github.com/cython/cython/issues/4100#issuecomment-814950627",
            "id": 814950627,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4100",
            "node_id": "MDEyOklzc3VlQ29tbWVudDgxNDk1MDYyNw==",
            "performed_via_github_app": null,
            "updated_at": "2021-04-07T14:17:54Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/814950627",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/194129?v=4",
                "events_url": "https://api.github.com/users/vstinner/events{/privacy}",
                "followers_url": "https://api.github.com/users/vstinner/followers",
                "following_url": "https://api.github.com/users/vstinner/following{/other_user}",
                "gists_url": "https://api.github.com/users/vstinner/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/vstinner",
                "id": 194129,
                "login": "vstinner",
                "node_id": "MDQ6VXNlcjE5NDEyOQ==",
                "organizations_url": "https://api.github.com/users/vstinner/orgs",
                "received_events_url": "https://api.github.com/users/vstinner/received_events",
                "repos_url": "https://api.github.com/users/vstinner/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/vstinner/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/vstinner/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/vstinner"
            }
        }
    ],
    "comments": 5,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/4100/comments",
    "created_at": "2021-04-07T12:51:53Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/4100/events",
    "html_url": "https://github.com/cython/cython/issues/4100",
    "id": 852377504,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/4100/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU4NTIzNzc1MDQ=",
    "number": 4100,
    "performed_via_github_app": null,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "[BUG] More Python 3.10 test failures",
    "updated_at": "2021-04-07T14:17:54Z",
    "url": "https://api.github.com/repos/cython/cython/issues/4100",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/194129?v=4",
        "events_url": "https://api.github.com/users/vstinner/events{/privacy}",
        "followers_url": "https://api.github.com/users/vstinner/followers",
        "following_url": "https://api.github.com/users/vstinner/following{/other_user}",
        "gists_url": "https://api.github.com/users/vstinner/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/vstinner",
        "id": 194129,
        "login": "vstinner",
        "node_id": "MDQ6VXNlcjE5NDEyOQ==",
        "organizations_url": "https://api.github.com/users/vstinner/orgs",
        "received_events_url": "https://api.github.com/users/vstinner/received_events",
        "repos_url": "https://api.github.com/users/vstinner/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/vstinner/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/vstinner/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/vstinner"
    }
}