{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "COLLABORATOR",
    "body": "<!--\r\n**PLEASE READ THIS FIRST:**\r\n- Do not use the bug and feature tracker for support requests. Use the `cython-users` mailing list instead.\r\n- Did you search for similar issues already? Please do, it helps to save us precious time that we otherwise could not invest into development.\r\n- Did you try the latest master branch or pre-release? It might already have what you want to report. Also see the [Changelog](https://github.com/cython/cython/blob/master/CHANGES.rst) regarding recent changes.\r\n-->\r\n\r\n**Describe the bug +To Reproduce**\r\n\r\nFrom the users mailing list (https://groups.google.com/g/cython-users/c/R4YQzdIOPSQ):\r\n\r\n```\r\nclass BaseModel:\r\n    pass\r\n\r\nclass Field:\r\n    def __init__(self, *args, **kwds):\r\n        pass\r\n\r\nclass ServiceRow(BaseModel):\r\n    \"\"\"An individual record.\"\"\"\r\n\r\n    service_id: int = Field(..., description=\"The ID for the service.\", alias=\"id\")\r\n    name: str = Field(..., description=\"Displayable Name for the service.\")\r\n```\r\n\r\nFails at runtime with\r\n```\r\nname: str = Field(..., description=\"Displayable Name for the service.\")\r\nTypeError: Expected str, got Field\r\n```\r\n\r\nGenerated C code includes\r\n```\r\nif (!(likely(PyString_CheckExact(__pyx_t_2))||((__pyx_t_2) == Py_None) || __Pyx_RaiseUnexpectedTypeError(\"str\", __pyx_t_2))) __PYX_ERR(0, 12, __pyx_L1_error)\r\n```\r\n\r\n**Expected behavior**\r\n\r\nIt's just regular Python code - it shouldn't enforce the types\r\n\r\n**Environment (please complete the following information):**\r\n - OS: Linux\r\n - Python version 3.8.9\r\n - Cython version: 3.0a7\r\n\r\n**Additional context**\r\n\r\nBisect suggests b2b81c9c5b87645c3f2a71322ead2ab8c9b7b567 (slightly unsurprisingly).\r\n",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "I can also add that\r\n```\r\n# cython: annotation_typing=False\r\n```\r\nadded to the top of the file does not seem to work around the issue either.",
            "created_at": "2021-05-27T08:15:35Z",
            "html_url": "https://github.com/cython/cython/issues/4196#issuecomment-849435061",
            "id": 849435061,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4196",
            "node_id": "MDEyOklzc3VlQ29tbWVudDg0OTQzNTA2MQ==",
            "performed_via_github_app": null,
            "updated_at": "2021-05-27T08:15:35Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/849435061",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/764829?v=4",
                "events_url": "https://api.github.com/users/stevenj/events{/privacy}",
                "followers_url": "https://api.github.com/users/stevenj/followers",
                "following_url": "https://api.github.com/users/stevenj/following{/other_user}",
                "gists_url": "https://api.github.com/users/stevenj/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/stevenj",
                "id": 764829,
                "login": "stevenj",
                "node_id": "MDQ6VXNlcjc2NDgyOQ==",
                "organizations_url": "https://api.github.com/users/stevenj/orgs",
                "received_events_url": "https://api.github.com/users/stevenj/received_events",
                "repos_url": "https://api.github.com/users/stevenj/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/stevenj/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/stevenj/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/stevenj"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/4196/comments",
    "created_at": "2021-05-27T06:46:28Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/4196/events",
    "html_url": "https://github.com/cython/cython/issues/4196",
    "id": 903288317,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/4196/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWU5MDMyODgzMTc=",
    "number": 4196,
    "performed_via_github_app": null,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "[BUG] Types are being enforced on non-cdef classes",
    "updated_at": "2021-05-27T08:15:35Z",
    "url": "https://api.github.com/repos/cython/cython/issues/4196",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
        "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
        "followers_url": "https://api.github.com/users/da-woods/followers",
        "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
        "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/da-woods",
        "id": 10536947,
        "login": "da-woods",
        "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
        "organizations_url": "https://api.github.com/users/da-woods/orgs",
        "received_events_url": "https://api.github.com/users/da-woods/received_events",
        "repos_url": "https://api.github.com/users/da-woods/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/da-woods"
    }
}