{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "<!--\r\n**PLEASE READ THIS FIRST:**\r\n- DO NOT use the bug and feature tracker for general questions and support requests.\r\n  Use the `cython-users` mailing list instead.\r\n  It has a wider audience, so you get more and better answers.\r\n- Did you search for similar issues already?\r\n  Please do, it helps to save us precious time that we otherwise could not invest into development.\r\n- Did you try the latest master branch or pre-release?\r\n  It might already have what you want to report.\r\n  Also see the [Changelog](https://github.com/cython/cython/blob/master/CHANGES.rst) regarding recent changes.\r\n-->\r\n\r\nHello up there. I've hit Python abort on a code that uses both memoryview slices and exception raised from inside closure. Please see below for details:\r\n\r\n\r\n```cython\r\ndef f(s):\r\n    g(s)\r\n\r\ncdef g(const unsigned char[::1]s):\r\n    cdef int i = 0\r\n    cdef int l = len(s)\r\n    def nextchar():\r\n        nonlocal i\r\n        if i >= l:\r\n            raise ValueError(\"END\")\r\n        c = s[i]\r\n        i += 1\r\n        return c\r\n\r\n    while 1:\r\n        c = nextchar()\r\n        print(c)\r\n\r\nf(b'123')\r\n```\r\n\r\n```console\r\n(neo) (py3.venv) (g.env) kirr@deca:~/tmp/trashme$ cythonize -i x.pyx && python -c 'import x'\r\nCompiling /home/kirr/tmp/trashme/x.pyx because it changed.\r\n[1/1] Cythonizing /home/kirr/tmp/trashme/x.pyx\r\n/home/kirr/src/wendelin/venv/py3.venv/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/kirr/tmp/trashme/x.pyx\r\n  tree = Parsing.p_module(s, pxd, full_module_name)\r\nrunning build_ext\r\nbuilding 'x' extension\r\ncreating /home/kirr/tmp/trashme/tmpapksgq8t/home\r\ncreating /home/kirr/tmp/trashme/tmpapksgq8t/home/kirr\r\ncreating /home/kirr/tmp/trashme/tmpapksgq8t/home/kirr/tmp\r\ncreating /home/kirr/tmp/trashme/tmpapksgq8t/home/kirr/tmp/trashme\r\nx86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/kirr/src/wendelin/venv/py3.venv/include -I/usr/include/python3.9 -c /home/kirr/tmp/trashme/x.c -o /home/kirr/tmp/trashme/tmpapksgq8t/home/kirr/tmp/trashme/x.o\r\nx86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /home/kirr/tmp/trashme/tmpapksgq8t/home/kirr/tmp/trashme/x.o -o /home/kirr/tmp/trashme/x.cpython-39-x86_64-linux-gnu.so\r\n\r\n49\r\n50\r\n51\r\nFatal Python error: __pyx_fatalerror: Acquisition count is 0 (line 2297)\r\nPython runtime state: initialized\r\nTraceback (most recent call last):\r\n  File \"x.pyx\", line 16, in x.g\r\n    c = nextchar()\r\n  File \"x.pyx\", line 10, in x.g.nextchar\r\n    raise ValueError(\"END\")\r\nValueError: END\r\nАварийный останов\r\n\r\n```\r\n\r\n**Expected behavior**\r\nValueError('END') raised but no `Fatal Python error: __pyx_fatalerror: Acquisition count is 0 (line 2297)`\r\n\r\n**Environment (please complete the following information):**\r\n - OS: Debian GNU/Linux 11\r\n - Python version 3.9.2\r\n - Cython version 0.29.30\r\n\r\n**Additional context**\r\n\r\nhttps://github.com/cython/cython/issues/4662 might be related.\r\n\r\nThanks beforehand,\r\nKirill\r\n",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/4798/comments",
    "created_at": "2022-05-19T12:22:35Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/4798/events",
    "html_url": "https://github.com/cython/cython/issues/4798",
    "id": 1241691898,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/4798/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5KArb6",
    "number": 4798,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/4798/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/4798/timeline",
    "title": "[BUG] __pyx_fatalerror: Acquisition count is 0  (with memoryview slices, closures and exceptions)",
    "updated_at": "2022-05-19T12:22:35Z",
    "url": "https://api.github.com/repos/cython/cython/issues/4798",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1794248?v=4",
        "events_url": "https://api.github.com/users/navytux/events{/privacy}",
        "followers_url": "https://api.github.com/users/navytux/followers",
        "following_url": "https://api.github.com/users/navytux/following{/other_user}",
        "gists_url": "https://api.github.com/users/navytux/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/navytux",
        "id": 1794248,
        "login": "navytux",
        "node_id": "MDQ6VXNlcjE3OTQyNDg=",
        "organizations_url": "https://api.github.com/users/navytux/orgs",
        "received_events_url": "https://api.github.com/users/navytux/received_events",
        "repos_url": "https://api.github.com/users/navytux/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/navytux/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/navytux/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/navytux"
    }
}