{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "<!--\r\n**PLEASE READ THIS FIRST:**\r\n- DO NOT use the bug and feature tracker for general questions and support requests.\r\n  Use the `cython-users` mailing list instead.\r\n  It has a wider audience, so you get more and better answers.\r\n- Did you search for similar issues already?\r\n  Please do, it helps to save us precious time that we otherwise could not invest into development.\r\n- Did you try the latest master branch or pre-release?\r\n  It might already have what you want to report.\r\n  Also see the [Changelog](https://github.com/cython/cython/blob/master/CHANGES.rst) regarding recent changes.\r\n-->\r\n\r\n**Describe the bug**\r\n`cpdef` function calling `cdef` function that raises in case of a return value of -1 would silently ignore the exception and simply skip executing the chunk of code starting from the `cdef` function.\r\n\r\nThis IMO is a *very* bad behavior/feature/bug, b/c it makes debugging very hard and confusing.\r\n\r\n**To Reproduce**\r\nCode to reproduce the behaviour:\r\n```\r\ncdef class Dummy:\r\n\r\n    cdef int test(self) nogil except -1:\r\n        return -1   # should raise\r\n\r\n\r\ncpdef void test() except *:\r\n    cdef Dummy d = Dummy()\r\n\r\n    print(\"before d.test\")\r\n    d.test()\r\n    print(\"called d.test\")\r\n```\r\n\r\n**Expected behavior**\r\nI would expect `d.test()` to raise and that exception gets propagated to the caller `test` as well.\r\n\r\nInstead, if you run the above, anything after line `d.test()` (inclusive) is simply ignored w/o any error/warning msgs!\r\n\r\n**Environment (please complete the following information):**\r\n - OS: Linux (Centos)\r\n - Python version 3.8\r\n - Cython version 3.0a10\r\n\r\n**Additional context**\r\nAdd any other context about the problem here.\r\n",
    "closed_at": "2022-06-12T13:07:48Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "No. You're misunderstanding how it works.\r\n\r\n```\r\ncdef int test(self) nogil except -1:\r\n    return -1   # should raise\r\n```\r\n\r\nWhat this says is: if Cython raises an error, then it'll use a value of -1 to indicate it to the caller.\r\nIt does not say that a value of -1 is converted into an exception. All `return -1` will do is confuse the caller (because it expects an exception to be set).\r\n\r\nWhat you want is something like:\r\n```\r\ncdef int test(self) nogil except -1:\r\n    raise ValueError\r\n```",
            "created_at": "2022-06-12T13:07:48Z",
            "html_url": "https://github.com/cython/cython/issues/4833#issuecomment-1153162461",
            "id": 1153162461,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4833",
            "node_id": "IC_kwDOABDGAc5Eu9zd",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1153162461/reactions"
            },
            "updated_at": "2022-06-12T13:07:48Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1153162461",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "> No. You're misunderstanding how it works.\r\n> \r\n> ```\r\n> cdef int test(self) nogil except -1:\r\n>     return -1   # should raise\r\n> ```\r\n> \r\n> What this says is: if Cython raises an error, then it'll use a value of -1 to indicate it to the caller. It does not say that a value of -1 is converted into an exception. All `return -1` will do is confuse the caller (because it expects an exception to be set).\r\n> \r\n> What you want is something like:\r\n> \r\n> ```\r\n> cdef int test(self) nogil except -1:\r\n>     raise ValueError\r\n> ```\r\n\r\nSo `except -1` is just a way for caller to realize that it needs to propagate the exception raised inside the `cdef` function. \r\n\r\nIf there's no exception detected, it behaves like a normal `cdef` function (i.e. just returns -1 and that's it)? \r\n\r\nBut then why `print(\"called d.test\")` part of the example above was skipped since there's no exception raised.",
            "created_at": "2022-06-12T13:18:29Z",
            "html_url": "https://github.com/cython/cython/issues/4833#issuecomment-1153165456",
            "id": 1153165456,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4833",
            "node_id": "IC_kwDOABDGAc5Eu-iQ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1153165456/reactions"
            },
            "updated_at": "2022-06-12T13:18:29Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1153165456",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/24363659?v=4",
                "events_url": "https://api.github.com/users/mlguruz/events{/privacy}",
                "followers_url": "https://api.github.com/users/mlguruz/followers",
                "following_url": "https://api.github.com/users/mlguruz/following{/other_user}",
                "gists_url": "https://api.github.com/users/mlguruz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mlguruz",
                "id": 24363659,
                "login": "mlguruz",
                "node_id": "MDQ6VXNlcjI0MzYzNjU5",
                "organizations_url": "https://api.github.com/users/mlguruz/orgs",
                "received_events_url": "https://api.github.com/users/mlguruz/received_events",
                "repos_url": "https://api.github.com/users/mlguruz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mlguruz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mlguruz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mlguruz"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> So except -1 is just a way for caller to realize that it needs to propagate the exception raised inside the cdef function.\r\n\r\nYes.\r\n\r\n> If there's no exception detected, it behaves like a normal cdef function (i.e. just returns -1 and that's it)?\r\n\r\nThis really isn't well-defined. It expects there to be an exception if you return -1. It may or may not check. You shouldn't rely on it.\r\n\r\nIf `-1` is a legitimate value to return then you should use `except ?-1` instead (which says \"a value of -1 might be an exception\")",
            "created_at": "2022-06-12T13:21:21Z",
            "html_url": "https://github.com/cython/cython/issues/4833#issuecomment-1153166132",
            "id": 1153166132,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4833",
            "node_id": "IC_kwDOABDGAc5Eu-s0",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1153166132/reactions"
            },
            "updated_at": "2022-06-12T13:21:21Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1153166132",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "> except ?-1\r\n\r\nI see... so let me summarize to make sure:\r\n\r\nFirst of all, picking `except -1` over `except *` (c only. no c++) is largely due the function return type (i.e. `int`) here, so faster (i.e. only check one value), and it's *only a signal* to the caller for checking and propagating exception(s). \r\n\r\nIf, for example, we wanna to *raise* if an index is -1, re-using the example above, we should just `raise` inside the `cdef` function to be safe, instead of `return -1` and counting on the caller to *treat* it as an exception (which it won't).  \r\n\r\nFinally, the reason why I saw the weird behavior (to me) above that the function runs but everything after `d.test()` is ignored, is b/c I was basically doing something **undefined**, i.e. telling the caller that there's an exception, but there's not, which is undefined.\r\n",
            "created_at": "2022-06-12T13:46:09Z",
            "html_url": "https://github.com/cython/cython/issues/4833#issuecomment-1153174667",
            "id": 1153174667,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4833",
            "node_id": "IC_kwDOABDGAc5EvAyL",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1153174667/reactions"
            },
            "updated_at": "2022-06-12T13:46:09Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1153174667",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/24363659?v=4",
                "events_url": "https://api.github.com/users/mlguruz/events{/privacy}",
                "followers_url": "https://api.github.com/users/mlguruz/followers",
                "following_url": "https://api.github.com/users/mlguruz/following{/other_user}",
                "gists_url": "https://api.github.com/users/mlguruz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mlguruz",
                "id": 24363659,
                "login": "mlguruz",
                "node_id": "MDQ6VXNlcjI0MzYzNjU5",
                "organizations_url": "https://api.github.com/users/mlguruz/orgs",
                "received_events_url": "https://api.github.com/users/mlguruz/received_events",
                "repos_url": "https://api.github.com/users/mlguruz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mlguruz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mlguruz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mlguruz"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Yes, it looks like you understand it correctly now.",
            "created_at": "2022-06-12T13:49:00Z",
            "html_url": "https://github.com/cython/cython/issues/4833#issuecomment-1153175403",
            "id": 1153175403,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4833",
            "node_id": "IC_kwDOABDGAc5EvA9r",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1153175403/reactions"
            },
            "updated_at": "2022-06-12T13:49:00Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1153175403",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "> Yes, it looks like you understand it correctly now.\r\n\r\nThank you very much! Really appreciate the great help! ",
            "created_at": "2022-06-12T14:00:33Z",
            "html_url": "https://github.com/cython/cython/issues/4833#issuecomment-1153178927",
            "id": 1153178927,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/4833",
            "node_id": "IC_kwDOABDGAc5EvB0v",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1153178927/reactions"
            },
            "updated_at": "2022-06-12T14:00:33Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1153178927",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/24363659?v=4",
                "events_url": "https://api.github.com/users/mlguruz/events{/privacy}",
                "followers_url": "https://api.github.com/users/mlguruz/followers",
                "following_url": "https://api.github.com/users/mlguruz/following{/other_user}",
                "gists_url": "https://api.github.com/users/mlguruz/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mlguruz",
                "id": 24363659,
                "login": "mlguruz",
                "node_id": "MDQ6VXNlcjI0MzYzNjU5",
                "organizations_url": "https://api.github.com/users/mlguruz/orgs",
                "received_events_url": "https://api.github.com/users/mlguruz/received_events",
                "repos_url": "https://api.github.com/users/mlguruz/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mlguruz/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mlguruz/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mlguruz"
            }
        }
    ],
    "comments": 6,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/4833/comments",
    "created_at": "2022-06-12T12:24:40Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2022-06-12T13:07:48Z",
            "event": "closed",
            "id": 6791417193,
            "node_id": "CE_lADOABDGAc5LnMUMzwAAAAGUzM1p",
            "performed_via_github_app": null,
            "state_reason": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/6791417193"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2022-06-12T13:08:03Z",
            "event": "labeled",
            "id": 6791417522,
            "label": {
                "color": "444444",
                "name": "R: worksforme"
            },
            "node_id": "LE_lADOABDGAc5LnMUMzwAAAAGUzM6y",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/6791417522"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/4833/events",
    "html_url": "https://github.com/cython/cython/issues/4833",
    "id": 1268565260,
    "labels": [
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425556354,
            "name": "R: worksforme",
            "node_id": "MDU6TGFiZWw0MjU1NTYzNTQ=",
            "url": "https://api.github.com/repos/cython/cython/labels/R:%20worksforme"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/4833/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5LnMUM",
    "number": 4833,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/4833/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/4833/timeline",
    "title": "[BUG] cdef `except -1` silently ignored by cpdef caller and not raised!",
    "updated_at": "2022-06-12T14:00:33Z",
    "url": "https://api.github.com/repos/cython/cython/issues/4833",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/24363659?v=4",
        "events_url": "https://api.github.com/users/mlguruz/events{/privacy}",
        "followers_url": "https://api.github.com/users/mlguruz/followers",
        "following_url": "https://api.github.com/users/mlguruz/following{/other_user}",
        "gists_url": "https://api.github.com/users/mlguruz/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/mlguruz",
        "id": 24363659,
        "login": "mlguruz",
        "node_id": "MDQ6VXNlcjI0MzYzNjU5",
        "organizations_url": "https://api.github.com/users/mlguruz/orgs",
        "received_events_url": "https://api.github.com/users/mlguruz/received_events",
        "repos_url": "https://api.github.com/users/mlguruz/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/mlguruz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mlguruz/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/mlguruz"
    }
}