{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Describe the bug\n\nIn a large pyc program these two lines\r\n\r\n                    with open(\"error_log.txt\", \"a\") as f:  \r\n                        f.write(f\"Failed: {var_1} {var_2}\\n\") \r\n\r\ncause this crash - when commented out, codes compiles without problems\r\n\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\Admin\\Documents\\Visual Studio 2019\\Projects\\DominionSolver\\setup.py\", line 41, in <module>\r\n    ext_modules = cythonize([\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Build\\Dependencies.py\", line 1129, in cythonize\r\n    cythonize_one(*args)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Build\\Dependencies.py\", line 1275, in cythonize_one\r\n    result = compile_single(pyx_file, options, full_module_name=full_module_name)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Main.py\", line 579, in compile_single\r\n    return run_pipeline(source, options, full_module_name)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Main.py\", line 503, in run_pipeline\r\n    err, enddata = Pipeline.run_pipeline(pipeline, source)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Pipeline.py\", line 397, in run_pipeline\r\n    data = run(phase, data)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Pipeline.py\", line 374, in run\r\n    return phase(data)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Pipeline.py\", line 52, in generate_pyx_code_stage\r\n    module_node.process_implementation(options, result)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\ModuleNode.py\", line 206, in process_implementation\r\n    self.generate_c_code(env, options, result)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\ModuleNode.py\", line 501, in generate_c_code\r\n    self.body.generate_function_definitions(env, code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 404, in generate_function_definitions\r\n    stat.generate_function_definitions(env, code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 404, in generate_function_definitions\r\n    stat.generate_function_definitions(env, code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 5366, in generate_function_definitions\r\n    self.body.generate_function_definitions(self.scope, code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 404, in generate_function_definitions\r\n    stat.generate_function_definitions(env, code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 3458, in generate_function_definitions\r\n    FuncDefNode.generate_function_definitions(self, env, code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 2157, in generate_function_definitions\r\n    self.generate_function_body(env, code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 1918, in generate_function_body\r\n    self.body.generate_execution_code(code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 410, in generate_execution_code\r\n    stat.generate_execution_code(code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 7156, in generate_execution_code\r\n    self.body.generate_execution_code(code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 410, in generate_execution_code\r\n    stat.generate_execution_code(code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 7156, in generate_execution_code\r\n    self.body.generate_execution_code(code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 410, in generate_execution_code\r\n    stat.generate_execution_code(code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 6974, in generate_execution_code\r\n    if_clause.generate_execution_code(code, end_label, is_last=i == last)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 7021, in generate_execution_code\r\n    self.body.generate_execution_code(code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 410, in generate_execution_code\r\n    stat.generate_execution_code(code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 7800, in generate_execution_code\r\n    self.body.generate_execution_code(code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 8296, in generate_execution_code\r\n    fresh_finally_clause().generate_execution_code(code)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\site-packages\\Cython\\Compiler\\Nodes.py\", line 8284, in fresh_finally_clause\r\n    node_copy = copy.deepcopy(node)\r\n\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\copy.py\", line 172, in deepcopy\r\n    y = _reconstruct(x, memo, *rv)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\copy.py\", line 271, in _reconstruct\r\n    state = deepcopy(state, memo)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\copy.py\", line 146, in deepcopy\r\n    y = copier(x, memo)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\copy.py\", line 231, in _deepcopy_dict\r\n    y[deepcopy(key, memo)] = deepcopy(value, memo)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\copy.py\", line 172, in deepcopy\r\n    y = _reconstruct(x, memo, *rv)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\copy.py\", line 271, in _reconstruct\r\n    state = deepcopy(state, memo)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\copy.py\", line 146, in deepcopy\r\n    y = copier(x, memo)\r\n  File \"C:\\Users\\Admin\\anaconda3\\envs\\dominion\\lib\\copy.py\", line 231, in _deepcopy_dict\r\n    y[deepcopy(key, memo)] = deepcopy(value, memo)\r\nrepeats until\r\nRecursionError: maximum recursion depth exceeded\r\n\n\n### Code to reproduce the behaviour:\n\n```cython\r\n# example code\r\n```\r\n\n\n### Expected behaviour\n\nno crash\n\n### Environment\n\nOS: Windows 10 Pro\r\nPython 3.10.4\r\nCython version 3.0.0a11\r\n\n\n### Additional context\n\n_No response_",
    "closed_at": "2022-09-10T09:22:18Z",
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "This definitely looks like a bug, but I can't reproduce it from the information given so it's unlikely to get fixed.\r\n\r\nIt'd be very useful if you could try to get this down to a small reproducible example.",
            "created_at": "2022-09-09T21:42:37Z",
            "html_url": "https://github.com/cython/cython/issues/5011#issuecomment-1242503715",
            "id": 1242503715,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5011",
            "node_id": "IC_kwDOABDGAc5KDxoj",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1242503715/reactions"
            },
            "updated_at": "2022-09-09T21:43:34Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1242503715",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "That will be quite tricky and my first try failed... What I could ascertain is that var_1 is an int and does not cause problems but var_2 is a npt.NDArray / cdef public int[:] and causes the crash. Does this help? ",
            "created_at": "2022-09-09T22:15:05Z",
            "html_url": "https://github.com/cython/cython/issues/5011#issuecomment-1242520305",
            "id": 1242520305,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5011",
            "node_id": "IC_kwDOABDGAc5KD1rx",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1242520305/reactions"
            },
            "updated_at": "2022-09-09T22:15:05Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1242520305",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/52322342?v=4",
                "events_url": "https://api.github.com/users/excubo-jg/events{/privacy}",
                "followers_url": "https://api.github.com/users/excubo-jg/followers",
                "following_url": "https://api.github.com/users/excubo-jg/following{/other_user}",
                "gists_url": "https://api.github.com/users/excubo-jg/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/excubo-jg",
                "id": 52322342,
                "login": "excubo-jg",
                "node_id": "MDQ6VXNlcjUyMzIyMzQy",
                "organizations_url": "https://api.github.com/users/excubo-jg/orgs",
                "received_events_url": "https://api.github.com/users/excubo-jg/received_events",
                "repos_url": "https://api.github.com/users/excubo-jg/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/excubo-jg/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/excubo-jg/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/excubo-jg"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Is `error_log.txt` empty/nonexistant at the moment error happens?\r\nGive an example of the `var_1` and `var_2`\r\n",
            "created_at": "2022-09-10T05:19:28Z",
            "html_url": "https://github.com/cython/cython/issues/5011#issuecomment-1242634905",
            "id": 1242634905,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5011",
            "node_id": "IC_kwDOABDGAc5KERqZ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1242634905/reactions"
            },
            "updated_at": "2022-09-10T05:19:28Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1242634905",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/52697657?v=4",
                "events_url": "https://api.github.com/users/0dminnimda/events{/privacy}",
                "followers_url": "https://api.github.com/users/0dminnimda/followers",
                "following_url": "https://api.github.com/users/0dminnimda/following{/other_user}",
                "gists_url": "https://api.github.com/users/0dminnimda/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/0dminnimda",
                "id": 52697657,
                "login": "0dminnimda",
                "node_id": "MDQ6VXNlcjUyNjk3NjU3",
                "organizations_url": "https://api.github.com/users/0dminnimda/orgs",
                "received_events_url": "https://api.github.com/users/0dminnimda/received_events",
                "repos_url": "https://api.github.com/users/0dminnimda/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/0dminnimda/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/0dminnimda/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/0dminnimda"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Is `error_log.txt` empty/nonexistant at the moment error happens?\r\n\r\nI don't think error_log.txt matters - it's a compilation error rather than a runtime error.",
            "created_at": "2022-09-10T05:40:47Z",
            "html_url": "https://github.com/cython/cython/issues/5011#issuecomment-1242637544",
            "id": 1242637544,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5011",
            "node_id": "IC_kwDOABDGAc5KESTo",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1242637544/reactions"
            },
            "updated_at": "2022-09-10T05:40:47Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1242637544",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "I have played around with this quite a bit and the smallest size I can limit it down is 1k LOC and 6 files... What puzzles me is that further deleting unrelated lines makes the error go away but I don't see a pattern what causes the problem. If you were willing to investigate further I could set up a repo and give you access",
            "created_at": "2022-09-10T08:01:29Z",
            "html_url": "https://github.com/cython/cython/issues/5011#issuecomment-1242662648",
            "id": 1242662648,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5011",
            "node_id": "IC_kwDOABDGAc5KEYb4",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1242662648/reactions"
            },
            "updated_at": "2022-09-10T08:01:29Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1242662648",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/52322342?v=4",
                "events_url": "https://api.github.com/users/excubo-jg/events{/privacy}",
                "followers_url": "https://api.github.com/users/excubo-jg/followers",
                "following_url": "https://api.github.com/users/excubo-jg/following{/other_user}",
                "gists_url": "https://api.github.com/users/excubo-jg/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/excubo-jg",
                "id": 52322342,
                "login": "excubo-jg",
                "node_id": "MDQ6VXNlcjUyMzIyMzQy",
                "organizations_url": "https://api.github.com/users/excubo-jg/orgs",
                "received_events_url": "https://api.github.com/users/excubo-jg/received_events",
                "repos_url": "https://api.github.com/users/excubo-jg/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/excubo-jg/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/excubo-jg/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/excubo-jg"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "It's just about possible that it's not a runaway recursion and just a deep recursion - Cython does work by traversing a tree recursively so it is possible to trigger recursion errors in some rare cases just by having a sufficiently complex source file. `a+b+c+d+e+f+...` will do it if you make it long enough...\r\n\r\nCould you try changing the recursion limit (https://docs.python.org/3/library/sys.html?highlight=sys#sys.setrecursionlimit) to make it a bit bigger and see if that fixes it - say 4000. If you put `sys.setrecursionlimit` in your setup.py that'll probably do it.\r\n\r\nFailing that, 1k LOC is better than nothing. It'd at least let me try to see if I can spot anything in the debugger. No promises of course (and definitely no promises of anything immediate) but I could have a look",
            "created_at": "2022-09-10T08:14:37Z",
            "html_url": "https://github.com/cython/cython/issues/5011#issuecomment-1242665264",
            "id": 1242665264,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5011",
            "node_id": "IC_kwDOABDGAc5KEZEw",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1242665264/reactions"
            },
            "updated_at": "2022-09-10T08:14:37Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1242665264",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "NONE",
            "body": "Many thanks for the hint - increasing the limit did process the original code base. Closing this",
            "created_at": "2022-09-10T09:22:18Z",
            "html_url": "https://github.com/cython/cython/issues/5011#issuecomment-1242679806",
            "id": 1242679806,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5011",
            "node_id": "IC_kwDOABDGAc5KEcn-",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1242679806/reactions"
            },
            "updated_at": "2022-09-10T09:22:18Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1242679806",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/52322342?v=4",
                "events_url": "https://api.github.com/users/excubo-jg/events{/privacy}",
                "followers_url": "https://api.github.com/users/excubo-jg/followers",
                "following_url": "https://api.github.com/users/excubo-jg/following{/other_user}",
                "gists_url": "https://api.github.com/users/excubo-jg/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/excubo-jg",
                "id": 52322342,
                "login": "excubo-jg",
                "node_id": "MDQ6VXNlcjUyMzIyMzQy",
                "organizations_url": "https://api.github.com/users/excubo-jg/orgs",
                "received_events_url": "https://api.github.com/users/excubo-jg/received_events",
                "repos_url": "https://api.github.com/users/excubo-jg/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/excubo-jg/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/excubo-jg/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/excubo-jg"
            }
        }
    ],
    "comments": 7,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5011/comments",
    "created_at": "2022-09-09T15:50:19Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/52322342?v=4",
                "events_url": "https://api.github.com/users/excubo-jg/events{/privacy}",
                "followers_url": "https://api.github.com/users/excubo-jg/followers",
                "following_url": "https://api.github.com/users/excubo-jg/following{/other_user}",
                "gists_url": "https://api.github.com/users/excubo-jg/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/excubo-jg",
                "id": 52322342,
                "login": "excubo-jg",
                "node_id": "MDQ6VXNlcjUyMzIyMzQy",
                "organizations_url": "https://api.github.com/users/excubo-jg/orgs",
                "received_events_url": "https://api.github.com/users/excubo-jg/received_events",
                "repos_url": "https://api.github.com/users/excubo-jg/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/excubo-jg/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/excubo-jg/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/excubo-jg"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2022-09-10T09:22:18Z",
            "event": "closed",
            "id": 7360673607,
            "node_id": "CE_lADOABDGAc5RikmXzwAAAAG2uvdH",
            "performed_via_github_app": null,
            "state_reason": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/7360673607"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5011/events",
    "html_url": "https://github.com/cython/cython/issues/5011",
    "id": 1368017303,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5011/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5RikmX",
    "number": 5011,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/5011/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "closed",
    "state_reason": "completed",
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5011/timeline",
    "title": "[BUG] RecursionError: maximum recursion depth exceeded",
    "updated_at": "2022-09-10T09:22:18Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5011",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/52322342?v=4",
        "events_url": "https://api.github.com/users/excubo-jg/events{/privacy}",
        "followers_url": "https://api.github.com/users/excubo-jg/followers",
        "following_url": "https://api.github.com/users/excubo-jg/following{/other_user}",
        "gists_url": "https://api.github.com/users/excubo-jg/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/excubo-jg",
        "id": 52322342,
        "login": "excubo-jg",
        "node_id": "MDQ6VXNlcjUyMzIyMzQy",
        "organizations_url": "https://api.github.com/users/excubo-jg/orgs",
        "received_events_url": "https://api.github.com/users/excubo-jg/received_events",
        "repos_url": "https://api.github.com/users/excubo-jg/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/excubo-jg/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/excubo-jg/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/excubo-jg"
    }
}