{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "### Describe the bug\r\n\r\nIf you use the `cimport` keyword in pure Python it doesn't work (correctly). However, the error message suggests that you should use the `cimport` keyword\r\n\r\n### Code to reproduce the behaviour:\r\n\r\n```cython\r\nfrom cython.operator cimport dereference\r\n```\r\n\r\nOutput is:\r\n\r\n```\r\nfrom cython.operator cimport dereference\r\n                     ^\r\n------------------------------------------------------------\r\n\r\nsomefilename.py:1:21: Expected 'import' or 'cimport'\r\n```\r\n\r\n### Expected behaviour\r\n\r\nA useful error message. This isn't quite as simple as it looks because the `cython` module wants to be imported, while most other thing want `from cython.cimports...`. Although given that this is at the parsing stage, it'd probably be sufficient to just write `expected \"import\"`\r\n\r\n### Environment\r\n\r\nCurrent master\r\n\r\n### Additional context\r\n\r\n_No response_",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5185/comments",
    "created_at": "2022-12-29T10:32:14Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2022-12-29T10:32:24Z",
            "event": "labeled",
            "id": 8125517489,
            "label": {
                "color": "444444",
                "name": "Error Reporting"
            },
            "node_id": "LE_lADOABDGAc5aN8B3zwAAAAHkUY6x",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/8125517489"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5185/events",
    "html_url": "https://github.com/cython/cython/issues/5185",
    "id": 1513603191,
    "labels": [
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425557478,
            "name": "Error Reporting",
            "node_id": "MDU6TGFiZWw0MjU1NTc0Nzg=",
            "url": "https://api.github.com/repos/cython/cython/labels/Error%20Reporting"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5185/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5aN8B3",
    "number": 5185,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/5185/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5185/timeline",
    "title": "[BUG] Misleading error message when trying to cimport in pure Python",
    "updated_at": "2022-12-29T10:33:40Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5185",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
        "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
        "followers_url": "https://api.github.com/users/da-woods/followers",
        "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
        "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/da-woods",
        "id": 10536947,
        "login": "da-woods",
        "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
        "organizations_url": "https://api.github.com/users/da-woods/orgs",
        "received_events_url": "https://api.github.com/users/da-woods/received_events",
        "repos_url": "https://api.github.com/users/da-woods/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/da-woods"
    }
}