{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Describe the bug\r\n\r\nTrying to compile a class with a **method** that both is **inline** and has a **fused type** as an argument fails.\r\n\r\nThe error you get is:\r\n```\r\ntest.c(8051): error C2129: static function 'PyObject *__pyx_f_4test_1C_method(__pyx_obj_4test_C *,double)' declared but not defined\r\ntest.c(1325): note: see declaration of '__pyx_f_4test_1C_method'\r\n```\r\n\r\nThe code that is generated that seems relevant:\r\n```c\r\nstruct __pyx_vtabstruct_4test_C {\r\n  PyObject *(*caller)(struct __pyx_obj_4test_C *);\r\n  PyObject *(*__pyx_fuse_0method)(struct __pyx_obj_4test_C *, int);\r\n  PyObject *(*__pyx_fuse_1method)(struct __pyx_obj_4test_C *, double);\r\n};\r\nstatic struct __pyx_vtabstruct_4test_C *__pyx_vtabptr_4test_C;\r\nstatic CYTHON_INLINE PyObject *__pyx_f_4test_1C_method(struct __pyx_obj_4test_C *, int);\r\nstatic CYTHON_INLINE PyObject *__pyx_f_4test_1C_method(struct __pyx_obj_4test_C *, double);\r\n\r\n(...)\r\n\r\n/* #### Code section: module_declarations ### */\r\nstatic CYTHON_INLINE PyObject *__pyx_fuse_0__pyx_f_4test_1C_method(CYTHON_UNUSED struct __pyx_obj_4test_C *__pyx_v_self, CYTHON_UNUSED int __pyx_v_val); /* proto*/\r\nstatic CYTHON_INLINE PyObject *__pyx_fuse_1__pyx_f_4test_1C_method(CYTHON_UNUSED struct __pyx_obj_4test_C *__pyx_v_self, CYTHON_UNUSED double __pyx_v_val); /* proto*/\r\nstatic PyObject *__pyx_f_4test_1C_caller(struct __pyx_obj_4test_C *__pyx_v_self); /* proto*/\r\n```\r\n\r\nLater on, both `__pyx_fuse_X__pyx_f_4test_1C_method` methods are defined but the call does not use the `__pyx_fuse_X` prefix:\r\n```c\r\n__pyx_t_1 = __pyx_f_4test_1C_method(__pyx_v_self, 5);\r\n```\r\n\r\n\r\nNote: doing the same for a cdef function (not within a class) works correctly because the function without the fuse prefix is not declared.\r\n\r\n### Code to reproduce the behaviour:\r\n\r\n```cython\r\nctypedef fused fused_type:\r\n    int\r\n    double\r\n\r\n\r\ncdef class C:\r\n    cdef inline method(self, fused_type val):\r\n        pass\r\n\r\n\r\n    # Fails with error C2129: static function 'PyObject *__pyx_f_4test_1C_method(__pyx_obj_4test_C *,double)' declared but not defined\r\n    cdef caller(self):\r\n        self.method(5)  # Does not compile\r\n\r\n\r\n# Same code within functions works correctly\r\ncdef inline ok_fun(fused_type val):\r\n    pass\r\n\r\n\r\ncdef main():\r\n    ok_fun(5)  # OK!\r\n    ok_fun(5.6)  # OK!\r\n```\r\n\r\n\r\n### Expected behaviour\r\n\r\n_No response_\r\n\r\n### OS\r\n\r\nWindows 10\r\n\r\n### Python version\r\n\r\n3.11.1\r\n\r\n### Cython version\r\n\r\n3.0.0b2\r\n\r\n### Additional context\r\n\r\nhttps://github.com/cython/cython/issues/5037 may be related, although the compilation error is different",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5416/comments",
    "created_at": "2023-05-01T21:37:11Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5416/events",
    "html_url": "https://github.com/cython/cython/issues/5416",
    "id": 1691440015,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5416/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5k0VOP",
    "number": 5416,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/5416/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5416/timeline",
    "title": "[BUG] inline methods with fused types generate a compiler error",
    "updated_at": "2023-05-01T21:40:20Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5416",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/1450333?v=4",
        "events_url": "https://api.github.com/users/overfl0/events{/privacy}",
        "followers_url": "https://api.github.com/users/overfl0/followers",
        "following_url": "https://api.github.com/users/overfl0/following{/other_user}",
        "gists_url": "https://api.github.com/users/overfl0/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/overfl0",
        "id": 1450333,
        "login": "overfl0",
        "node_id": "MDQ6VXNlcjE0NTAzMzM=",
        "organizations_url": "https://api.github.com/users/overfl0/orgs",
        "received_events_url": "https://api.github.com/users/overfl0/received_events",
        "repos_url": "https://api.github.com/users/overfl0/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/overfl0/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/overfl0/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/overfl0"
    }
}