{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "MEMBER",
    "body": "### Describe the bug\r\n\r\nPEP-669 (https://peps.python.org/pep-0669/) and its implementation in https://github.com/python/cpython/pull/103083 change the internals of CPython's tracing in Py3.12. We need to adapt. Currently, profiling fails in Py3.12.\r\n\r\nCompilation was already fixed in https://github.com/cython/cython/commit/03c498d3142ccee2da258c540e96f12c863159fc (#5450), but that doesn't make the feature work again.\r\n\r\nTest failure:\r\n\r\n<details>\r\n\r\n```\r\n======================================================================\r\nFAIL: pstats_profile_test ()\r\nDoctest: pstats_profile_test\r\n----------------------------------------------------------------------\r\nTraceback (most recent call last):\r\n  File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 2228, in runTest\r\n    raise self.failureException(self.format_failure(new.getvalue()))\r\nAssertionError: Failed doctest test for pstats_profile_test\r\n  File \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 1, in pstats_profile_test\r\n\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 8, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_def']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[5]>\", line 1, in <module>\r\n        short_stats['f_def']\r\n        ~~~~~~~~~~~^^^^^^^^^\r\n    KeyError: 'f_def'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 10, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_cdef']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[6]>\", line 1, in <module>\r\n        short_stats['f_cdef']\r\n        ~~~~~~~~~~~^^^^^^^^^^\r\n    KeyError: 'f_cdef'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 12, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_cpdef']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[7]>\", line 1, in <module>\r\n        short_stats['f_cpdef']\r\n        ~~~~~~~~~~~^^^^^^^^^^^\r\n    KeyError: 'f_cpdef'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 14, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_inline']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[8]>\", line 1, in <module>\r\n        short_stats['f_inline']\r\n        ~~~~~~~~~~~^^^^^^^^^^^^\r\n    KeyError: 'f_inline'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 16, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_inline_prof']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[9]>\", line 1, in <module>\r\n        short_stats['f_inline_prof']\r\n        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^\r\n    KeyError: 'f_inline_prof'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 22, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_raise']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[11]>\", line 1, in <module>\r\n        short_stats['f_raise']\r\n        ~~~~~~~~~~~^^^^^^^^^^^\r\n    KeyError: 'f_raise'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 25, in pstats_profile_test\r\nFailed example:\r\n    short_stats['withgil_prof']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[12]>\", line 1, in <module>\r\n        short_stats['withgil_prof']\r\n        ~~~~~~~~~~~^^^^^^^^^^^^^^^^\r\n    KeyError: 'withgil_prof'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 41, in pstats_profile_test\r\nFailed example:\r\n    short_stats['f_raise']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[16]>\", line 1, in <module>\r\n        short_stats['f_raise']\r\n        ~~~~~~~~~~~^^^^^^^^^^^\r\n    KeyError: 'f_raise'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 44, in pstats_profile_test\r\nFailed example:\r\n    short_stats['m_def']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[17]>\", line 1, in <module>\r\n        short_stats['m_def']\r\n        ~~~~~~~~~~~^^^^^^^^^\r\n    KeyError: 'm_def'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 46, in pstats_profile_test\r\nFailed example:\r\n    short_stats['m_cdef']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[18]>\", line 1, in <module>\r\n        short_stats['m_cdef']\r\n        ~~~~~~~~~~~^^^^^^^^^^\r\n    KeyError: 'm_cdef'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 48, in pstats_profile_test\r\nFailed example:\r\n    short_stats['m_cpdef'] - (200 if CPDEF_METHODS_COUNT_TWICE else 0)  # FIXME!\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[19]>\", line 1, in <module>\r\n        short_stats['m_cpdef'] - (200 if CPDEF_METHODS_COUNT_TWICE else 0)  # FIXME!\r\n        ~~~~~~~~~~~^^^^^^^^^^^\r\n    KeyError: 'm_cpdef'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 56, in pstats_profile_test\r\nFailed example:\r\n    sorted(callees(s, 'test_profile'))  #doctest: +NORMALIZE_WHITESPACE\r\nExpected:\r\n    ['f_cdef', 'f_cpdef', 'f_def',\r\n     'f_inline', 'f_inline_prof',\r\n     'f_raise',\r\n     'm_cdef', 'm_cpdef', 'm_def',\r\n     'withgil_prof']\r\nGot:\r\n    []\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 66, in pstats_profile_test\r\nFailed example:\r\n    short_stats['generator']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[25]>\", line 1, in <module>\r\n        short_stats['generator']\r\n        ~~~~~~~~~~~^^^^^^^^^^^^^\r\n    KeyError: 'generator'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 69, in pstats_profile_test\r\nFailed example:\r\n    short_stats['generator_exception']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[26]>\", line 1, in <module>\r\n        short_stats['generator_exception']\r\n        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^\r\n    KeyError: 'generator_exception'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 72, in pstats_profile_test\r\nFailed example:\r\n    short_stats['genexpr']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[27]>\", line 1, in <module>\r\n        short_stats['genexpr']\r\n        ~~~~~~~~~~~^^^^^^^^^^^\r\n    KeyError: 'genexpr'\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 75, in pstats_profile_test\r\nFailed example:\r\n    sorted(callees(s, 'test_generators'))\r\nExpected:\r\n    ['call_generator', 'call_generator_exception', 'generator_expr']\r\nGot:\r\n    []\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 78, in pstats_profile_test\r\nFailed example:\r\n    list(callees(s, 'call_generator'))\r\nExpected:\r\n    ['generator']\r\nGot:\r\n    []\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 87, in pstats_profile_test\r\nFailed example:\r\n    list(callees(s, 'generator_expr'))\r\nExpected:\r\n    ['genexpr']\r\nGot:\r\n    []\r\n----------------------------------------------------------------------\r\nFile \"/home/runner/work/cython/cython/TEST_TMP/6/run/c/pstats_profile_test/pstats_profile_test.cpython-312-x86_64-linux-gnu.so\", line 107, in pstats_profile_test\r\nFailed example:\r\n    python_stats_dict['python_generator'] == cython_stats_dict['generator']\r\nException raised:\r\n    Traceback (most recent call last):\r\n      File \"/opt/hostedtoolcache/Python/3.12.0-beta.1/x64/lib/python3.12/doctest.py\", line 1357, in __run\r\n        exec(compile(example.source, filename, \"single\",\r\n      File \"<doctest pstats_profile_test[42]>\", line 1, in <module>\r\n        python_stats_dict['python_generator'] == cython_stats_dict['generator']\r\n                                                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\r\n    KeyError: 'generator'\r\n```\r\n</details>\r\n\r\n### Code to reproduce the behaviour:\r\n\r\n_No response_\r\n\r\n### Expected behaviour\r\n\r\n_No response_\r\n\r\n### OS\r\n\r\n_No response_\r\n\r\n### Python version\r\n\r\n3.12.0b1\r\n\r\n### Cython version\r\n\r\ncurrent master (3.0.0b3)\r\n\r\n### Additional context\r\n\r\n_No response_",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "Detail tags and triple backticks need to be separated by a newline for the rendering to not be broken.",
            "created_at": "2023-06-06T09:02:47Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1578245707",
            "id": 1578245707,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5eEh5L",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1578245707/reactions"
            },
            "updated_at": "2023-11-12T08:28:03Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1578245707",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/33685575?v=4",
                "events_url": "https://api.github.com/users/h-vetinari/events{/privacy}",
                "followers_url": "https://api.github.com/users/h-vetinari/followers",
                "following_url": "https://api.github.com/users/h-vetinari/following{/other_user}",
                "gists_url": "https://api.github.com/users/h-vetinari/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/h-vetinari",
                "id": 33685575,
                "login": "h-vetinari",
                "node_id": "MDQ6VXNlcjMzNjg1NTc1",
                "organizations_url": "https://api.github.com/users/h-vetinari/orgs",
                "received_events_url": "https://api.github.com/users/h-vetinari/received_events",
                "repos_url": "https://api.github.com/users/h-vetinari/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/h-vetinari/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/h-vetinari/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/h-vetinari"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "Is there a chance that this could be in before the final release of 3.12? Also will this functionality be restored for 0.2.x version?",
            "created_at": "2023-08-29T04:27:51Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1696746901",
            "id": 1696746901,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5lIk2V",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1696746901/reactions"
            },
            "updated_at": "2023-08-29T04:27:51Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1696746901",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/44142765?v=4",
                "events_url": "https://api.github.com/users/zoj613/events{/privacy}",
                "followers_url": "https://api.github.com/users/zoj613/followers",
                "following_url": "https://api.github.com/users/zoj613/following{/other_user}",
                "gists_url": "https://api.github.com/users/zoj613/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/zoj613",
                "id": 44142765,
                "login": "zoj613",
                "node_id": "MDQ6VXNlcjQ0MTQyNzY1",
                "organizations_url": "https://api.github.com/users/zoj613/orgs",
                "received_events_url": "https://api.github.com/users/zoj613/received_events",
                "repos_url": "https://api.github.com/users/zoj613/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/zoj613/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/zoj613/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/zoj613"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> Is there a chance that this could be in before the final release of 3.12?\r\n\r\nIf someone repairs it in time, then yes. Investigations and/or PR is welcome.\r\n\r\nBasically, someone has to figure out how tracing can be done in Python 3.12 now. The CPython project broke their C-API, so they probably have a (documented?) idea somewhere how to migrate.\r\n\r\n\r\n> will this functionality be restored for 0.2.x version?\r\n\r\nThis is out of scope for future 0.29.x releases. We could add an explicit C warning there, though, when users try to use tracing in Py3.12. You can use Python 3.11 for profiling/tracing with 0.29.x.",
            "created_at": "2023-08-29T07:17:13Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1696899337",
            "id": 1696899337,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5lJKEJ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 1,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 1,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1696899337/reactions"
            },
            "updated_at": "2023-08-29T07:17:13Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1696899337",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "Quote from @da-woods in https://github.com/cython/cython/issues/5813\r\n\r\nProfiling on Py3.12+ is currently broken. Here are my notes from looking into it:\r\n\r\n* `PyEval_SetProfile` is now \"legacy\". It still works, and I believe Cython would still interact correctly with it if it were used. However, the standard library profile modules don't use it.\r\n* The current preferred way is via [`sys.monitoring`](https://docs.python.org/3/library/sys.monitoring.html#module-sys.monitoring), and this is what profile/cProfile do.\r\n* `PyEval_SetProfile` sets up functions using the new \"monitoring\" approach, however, things that use the new \"monitoring\" approach don't trigger the old `PyEval_SetProfile` way. Therefore, if we want to interact with all profiling tools we really need to use the new \"monitoring\" approach.\r\n* I think the right thing to do would be to call [`_Py_call_instrumentation`](https://github.com/python/cpython/blob/fa84e5fe0a3bd8e77c33b20867d71ac6bee270f9/Python/instrumentation.c#L1035C1) (or something similar). Unfortunately these are internal symbols so fail at the link stage (even if include the internal headers).\r\n* There doesn't seem to be an easy way to check if profiling is enabled. However, `_Py_call_instrumentation` looks to return very quickly if it isn't, so I think that's OK.\r\n* The linking errors are largely where I got stuck - there doesn't seem to be any accessible way to trigger a profiling event manually.",
            "created_at": "2023-11-12T08:28:18Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1807054938",
            "id": 1807054938,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5rtXha",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1807054938/reactions"
            },
            "updated_at": "2023-11-12T08:28:18Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1807054938",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I created https://github.com/python/cpython/issues/111997 for designing a new signalling C-API in CPython.",
            "created_at": "2023-11-12T08:29:38Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1807055254",
            "id": 1807055254,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5rtXmW",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1807055254/reactions"
            },
            "updated_at": "2023-11-12T08:29:38Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1807055254",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "My proposal for now is just to remove the test from Python 3.12: https://github.com/cython/cython/pull/5815.\r\n\r\nI suspect if people really needed to profile Cython+Python 3.12 they could cprofile/profile from Python 3.11 and it'd work (because they'd use the \"legacy\" method). But I don't think that's something we should provide ourself.",
            "created_at": "2023-11-12T13:38:20Z",
            "html_url": "https://github.com/cython/cython/issues/5470#issuecomment-1807131600",
            "id": 1807131600,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5470",
            "node_id": "IC_kwDOABDGAc5rtqPQ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1807131600/reactions"
            },
            "updated_at": "2023-11-12T13:38:20Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1807131600",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        }
    ],
    "comments": 6,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5470/comments",
    "created_at": "2023-06-06T08:40:46Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-06-06T08:40:46Z",
            "event": "labeled",
            "id": 9443295515,
            "label": {
                "color": "444444",
                "name": "defect"
            },
            "node_id": "LE_lADOABDGAc5n6c3nzwAAAAIy3UEb",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9443295515"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-06-06T08:40:46Z",
            "event": "labeled",
            "id": 9443295519,
            "label": {
                "color": "444444",
                "name": "Python Semantics"
            },
            "node_id": "LE_lADOABDGAc5n6c3nzwAAAAIy3UEf",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9443295519"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-06-06T08:40:46Z",
            "event": "milestoned",
            "id": 9443295538,
            "milestone": {
                "title": "3.0"
            },
            "node_id": "MIE_lADOABDGAc5n6c3nzwAAAAIy3UEy",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9443295538"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-07-23T13:00:24Z",
            "event": "demilestoned",
            "id": 9892738208,
            "milestone": {
                "title": "3.0"
            },
            "node_id": "DEME_lADOABDGAc5n6c3nzwAAAAJNpzSg",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9892738208"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-07-23T13:00:24Z",
            "event": "milestoned",
            "id": 9892738211,
            "milestone": {
                "title": "3.0.x"
            },
            "node_id": "MIE_lADOABDGAc5n6c3nzwAAAAJNpzSj",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/9892738211"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-11-12T08:28:18Z",
            "event": "mentioned",
            "id": 10934032618,
            "node_id": "MEE_lADOABDGAc5n6c3nzwAAAAKLuBjq",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10934032618"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-11-12T08:28:18Z",
            "event": "subscribed",
            "id": 10934032620,
            "node_id": "SE_lADOABDGAc5n6c3nzwAAAAKLuBjs",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10934032620"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5470/events",
    "html_url": "https://github.com/cython/cython/issues/5470",
    "id": 1743375847,
    "labels": [
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425553654,
            "name": "defect",
            "node_id": "MDU6TGFiZWw0MjU1NTM2NTQ=",
            "url": "https://api.github.com/repos/cython/cython/labels/defect"
        },
        {
            "color": "444444",
            "default": false,
            "description": null,
            "id": 425556315,
            "name": "Python Semantics",
            "node_id": "MDU6TGFiZWw0MjU1NTYzMTU=",
            "url": "https://api.github.com/repos/cython/cython/labels/Python%20Semantics"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5470/labels{/name}",
    "locked": false,
    "milestone": {
        "closed_at": null,
        "closed_issues": 2,
        "created_at": "2023-07-23T12:57:42Z",
        "creator": {
            "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
            "events_url": "https://api.github.com/users/scoder/events{/privacy}",
            "followers_url": "https://api.github.com/users/scoder/followers",
            "following_url": "https://api.github.com/users/scoder/following{/other_user}",
            "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
            "gravatar_id": "",
            "html_url": "https://github.com/scoder",
            "id": 491659,
            "login": "scoder",
            "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
            "organizations_url": "https://api.github.com/users/scoder/orgs",
            "received_events_url": "https://api.github.com/users/scoder/received_events",
            "repos_url": "https://api.github.com/users/scoder/repos",
            "site_admin": false,
            "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
            "type": "User",
            "url": "https://api.github.com/users/scoder"
        },
        "description": "",
        "due_on": null,
        "html_url": "https://github.com/cython/cython/milestone/99",
        "id": 9687005,
        "labels_url": "https://api.github.com/repos/cython/cython/milestones/99/labels",
        "node_id": "MI_kwDOABDGAc4Ak8_d",
        "number": 99,
        "open_issues": 15,
        "state": "open",
        "title": "3.0.x",
        "updated_at": "2023-11-07T18:37:27Z",
        "url": "https://api.github.com/repos/cython/cython/milestones/99"
    },
    "node_id": "I_kwDOABDGAc5n6c3n",
    "number": 5470,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 1,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 1,
        "url": "https://api.github.com/repos/cython/cython/issues/5470/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5470/timeline",
    "title": "[BUG] Profiling/tracing fails in Py3.12",
    "updated_at": "2023-11-12T13:38:20Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5470",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/491659?v=4",
        "events_url": "https://api.github.com/users/scoder/events{/privacy}",
        "followers_url": "https://api.github.com/users/scoder/followers",
        "following_url": "https://api.github.com/users/scoder/following{/other_user}",
        "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/scoder",
        "id": 491659,
        "login": "scoder",
        "node_id": "MDQ6VXNlcjQ5MTY1OQ==",
        "organizations_url": "https://api.github.com/users/scoder/orgs",
        "received_events_url": "https://api.github.com/users/scoder/received_events",
        "repos_url": "https://api.github.com/users/scoder/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/scoder"
    }
}