{
    "active_lock_reason": null,
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "### Describe the bug\r\n\r\nIf I create a Cython file containing just ``cimport numpy`` and try and compile it using CYTHON_LIMITED_API, I get a few errors:\r\n\r\n```\r\n      /home/tom/python/dev/lib/python3.11/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning \"Using deprecated NumPy API, disable it with \" \"#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION\" [-Wcpp]\r\n         17 | #warning \"Using deprecated NumPy API, disable it with \" \\\r\n            |  ^~~~~~~\r\n      In file included from test_cython/example.c:1189:\r\n      /home/tom/python/dev/lib/python3.11/site-packages/numpy/core/include/numpy/arrayscalars.h:140:9: error: unknown type name ‘PyUnicodeObject’\r\n        140 |         PyUnicodeObject base;\r\n            |         ^~~~~~~~~~~~~~~\r\n      test_cython/example.c: In function ‘__pyx_f_5numpy_import_array’:\r\n      test_cython/example.c:3202:93: error: invalid use of undefined type ‘struct _typeobject’\r\n       3202 |     __pyx_t_4 = __Pyx_PyErr_ExceptionMatches(((PyObject *)(&((PyTypeObject*)PyExc_Exception)[0])));\r\n            |                                                                                             ^\r\n      test_cython/example.c:1806:67: note: in definition of macro ‘__Pyx_PyErr_ExceptionMatches’\r\n       1806 | #define __Pyx_PyErr_ExceptionMatches(err)  PyErr_ExceptionMatches(err)\r\n            |                                                                   ^~~\r\n      test_cython/example.c: In function ‘__pyx_f_5numpy_import_umath’:\r\n      test_cython/example.c:3334:93: error: invalid use of undefined type ‘struct _typeobject’\r\n       3334 |     __pyx_t_4 = __Pyx_PyErr_ExceptionMatches(((PyObject *)(&((PyTypeObject*)PyExc_Exception)[0])));\r\n            |                                                                                             ^\r\n      test_cython/example.c:1806:67: note: in definition of macro ‘__Pyx_PyErr_ExceptionMatches’\r\n       1806 | #define __Pyx_PyErr_ExceptionMatches(err)  PyErr_ExceptionMatches(err)\r\n            |                                                                   ^~~\r\n      test_cython/example.c: In function ‘__pyx_f_5numpy_import_ufunc’:\r\n      test_cython/example.c:3466:93: error: invalid use of undefined type ‘struct _typeobject’\r\n       3466 |     __pyx_t_4 = __Pyx_PyErr_ExceptionMatches(((PyObject *)(&((PyTypeObject*)PyExc_Exception)[0])));\r\n            |                                                                                             ^\r\n      test_cython/example.c:1806:67: note: in definition of macro ‘__Pyx_PyErr_ExceptionMatches’\r\n       1806 | #define __Pyx_PyErr_ExceptionMatches(err)  PyErr_ExceptionMatches(err)\r\n            |                                                                   ^~~\r\n      test_cython/example.c: In function ‘__Pyx_modinit_type_import_code’:\r\n      test_cython/example.c:3860:10: error: invalid application of ‘sizeof’ to incomplete type ‘PyTypeObject’ {aka ‘struct _typeobject’}\r\n       3860 |   sizeof(PyTypeObject), __PYX_GET_STRUCT_ALIGNMENT_3_0_2(PyTypeObject),\r\n            |          ^~~~~~~~~~~~\r\n      test_cython/example.c:3860:58: error: invalid application of ‘__alignof__’ to incomplete type ‘PyTypeObject’ {aka ‘struct _typeobject’}\r\n       3860 |   sizeof(PyTypeObject), __PYX_GET_STRUCT_ALIGNMENT_3_0_2(PyTypeObject),\r\n            |                                                          ^~~~~~~~~~~~\r\n      test_cython/example.c:1906:53: note: in definition of macro ‘__PYX_GET_STRUCT_ALIGNMENT_3_0_2’\r\n       1906 | #define __PYX_GET_STRUCT_ALIGNMENT_3_0_2(s) alignof(s)\r\n            |                                                     ^\r\n      error: command '/usr/lib/ccache/x86_64-linux-gnu-gcc' failed with exit code 1\r\n      [end of output]\r\n```\r\n\r\n(some are warnings that are probably fine but there are some real errors)\r\n\r\n### Code to reproduce the behaviour:\r\n\r\n```cython\r\ncimport numpy\r\n```\r\n\r\nSee https://github.com/astrofrog/limited-api-experiments for a repo including this as a mini-package that can be built. The errors above can be reproduced by running:\r\n\r\n```\r\npython -m build --wheel\r\n```\r\n\r\n### Expected behaviour\r\n\r\nThe compilation should succeed\r\n\r\n### OS\r\n\r\nLinux\r\n\r\n### Python version\r\n\r\n3.11\r\n\r\n### Cython version\r\n\r\ndev\r\n\r\n### Additional context\r\n\r\nI've run into the typeobject error before when using the limited API and in the past the workaround has been to define this in the CI files:\r\n\r\nhttps://github.com/liberfa/pyerfa/blob/da319b5c4447070c3481dff487945b422e3e2aed/erfa/ufunc.c.templ#L20-L29\r\n\r\nand a relevant numpy issue is https://github.com/numpy/numpy/issues/16970 - I'm not sure how to apply this workaround here though.\r\n\r\n",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "MEMBER",
            "body": "The first error\r\n\r\n```\r\n/home/tom/python/dev/lib/python3.11/site-packages/numpy/core/include/numpy/arrayscalars.h:140:9: error: unknown type name ‘PyUnicodeObject’\r\n        140 |         PyUnicodeObject base;\r\n            |         ^~~~~~~~~~~~~~~\r\n```\r\n\r\ncomes from Numpy. I don't think we can do anything to fix those. It doesn't obviously look like https://github.com/numpy/numpy/issues/16970 though.\r\n\r\nMost of the others look like issues with generating exception checks and don't look specific to Numpy. Those would be well worth fixing because they probably fix quite a bit of code.\r\n\r\n",
            "created_at": "2023-09-12T17:01:44Z",
            "html_url": "https://github.com/cython/cython/issues/5697#issuecomment-1716109982",
            "id": 1716109982,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5697",
            "node_id": "IC_kwDOABDGAc5mScKe",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1716109982/reactions"
            },
            "updated_at": "2023-09-12T17:01:44Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1716109982",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "```\r\ntest_cython/example.c: In function ‘__Pyx_modinit_type_import_code’:\r\n      test_cython/example.c:3860:10: error: invalid application of ‘sizeof’ to incomplete type ‘PyTypeObject’ {aka ‘struct _typeobject’}\r\n       3860 |   sizeof(PyTypeObject), __PYX_GET_STRUCT_ALIGNMENT_3_0_2(PyTypeObject),\r\n            |          ^~~~~~~~~~~~\r\n      test_cython/example.c:3860:58: error: invalid application of ‘__alignof__’ to incomplete type ‘PyTypeObject’ {aka ‘struct _typeobject’}\r\n       3860 |   sizeof(PyTypeObject), __PYX_GET_STRUCT_ALIGNMENT_3_0_2(PyTypeObject),\r\n            |                                                          ^~~~~~~~~~~~\r\n      test_cython/example.c:1906:53: note: in definition of macro ‘__PYX_GET_STRUCT_ALIGNMENT_3_0_2’\r\n       1906 | #define __PYX_GET_STRUCT_ALIGNMENT_3_0_2(s) alignof(s)\r\n```\r\n\r\nThis is quite a challenging problem I think.\r\n\r\nThe issue is that `from cpython cimport *` (or similar) ends up importing a manual cdef class wrapping of typeobject. See https://github.com/cython/cython/issues/5634. The issue here is that it isn't just about fixing our code generation to work with the limited API.  Instead it seems like our wrapping of CPython uses features that are likely incompatible with the limited API. We therefore either have to break these for all our existing users or accept that anything that does `cimport cpython` (with `cimport numpy` does indirectly) is likely broken with the limited API.\r\n\r\nI haven't got a good answer for that at this stage, but I think code-generation bugs have to be the priority for now.",
            "created_at": "2023-09-12T20:17:48Z",
            "html_url": "https://github.com/cython/cython/issues/5697#issuecomment-1716365370",
            "id": 1716365370,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5697",
            "node_id": "IC_kwDOABDGAc5mTag6",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1716365370/reactions"
            },
            "updated_at": "2023-09-12T20:17:48Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1716365370",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "I've made a PR for the easy bit of this (which practically will fix any `except Exception` in the limited API)",
            "created_at": "2023-09-12T21:09:58Z",
            "html_url": "https://github.com/cython/cython/issues/5697#issuecomment-1716445525",
            "id": 1716445525,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5697",
            "node_id": "IC_kwDOABDGAc5mTuFV",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1716445525/reactions"
            },
            "updated_at": "2023-09-12T21:09:58Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1716445525",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "> The first error\r\n  ```\r\n  /home/tom/python/dev/lib/python3.11/site-packages/numpy/core/include/numpy. /arrayscalars.h:140:9: error: unknown type name ‘PyUnicodeObject’\r\n          140 |         PyUnicodeObject base;\r\n              |         ^~~~~~~~~~~~~~~\r\n  ```\r\n>  comes from Numpy.\r\n\r\nIs there a way to create a small reproducer for just this part of the issue?",
            "created_at": "2023-12-21T06:30:09Z",
            "html_url": "https://github.com/cython/cython/issues/5697#issuecomment-1865608201",
            "id": 1865608201,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5697",
            "node_id": "IC_kwDOABDGAc5vMuwJ",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1865608201/reactions"
            },
            "updated_at": "2023-12-21T06:30:09Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1865608201",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/823911?v=4",
                "events_url": "https://api.github.com/users/mattip/events{/privacy}",
                "followers_url": "https://api.github.com/users/mattip/followers",
                "following_url": "https://api.github.com/users/mattip/following{/other_user}",
                "gists_url": "https://api.github.com/users/mattip/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mattip",
                "id": 823911,
                "login": "mattip",
                "node_id": "MDQ6VXNlcjgyMzkxMQ==",
                "organizations_url": "https://api.github.com/users/mattip/orgs",
                "received_events_url": "https://api.github.com/users/mattip/received_events",
                "repos_url": "https://api.github.com/users/mattip/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mattip/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mattip/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mattip"
            }
        },
        {
            "author_association": "MEMBER",
            "body": "> just this part of the issue\r\n\r\nI think you either want to use the reproducer given in https://github.com/astrofrog/limited-api-experiments and build it with the https://github.com/cython/cython/pull/5871 branch of Cython.\r\n\r\nOr you probably just want to compile\r\n\r\n```\r\ncdef extern from \"numpy/arrayscalars.h\":\r\n    pass\r\n```\r\n\r\n(probably using the build script from the linked reproducer).",
            "created_at": "2023-12-21T08:20:04Z",
            "html_url": "https://github.com/cython/cython/issues/5697#issuecomment-1865843435",
            "id": 1865843435,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5697",
            "node_id": "IC_kwDOABDGAc5vNoLr",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1865843435/reactions"
            },
            "updated_at": "2023-12-21T08:20:04Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1865843435",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            }
        },
        {
            "author_association": "CONTRIBUTOR",
            "body": "I tried this pyx file on that branch\r\n```cython\r\n\"\"\"\r\nMake sure cython can compile in limited API mode\r\n\"\"\"\r\n\r\ncdef extern from \"numpy/arrayobject.h\":\r\n    pass\r\ncdef extern from \"numpy/arrayscalars.h\":\r\n    pass\r\n```\r\n\r\nwith this diff to the NumPy headers to avoid `PyUnicodeScalarObject`\r\n```diff\r\ndiff --git a/numpy/_core/include/numpy/arrayscalars.h b/numpy/_core/include/numpy/arrayscalars.h\r\nindex 258bf95b62..9ad7ddb19b 100644\r\n--- a/numpy/_core/include/numpy/arrayscalars.h\r\n+++ b/numpy/_core/include/numpy/arrayscalars.h\r\n@@ -135,6 +135,7 @@ typedef struct {\r\n } PyScalarObject;\r\n \r\n #define PyStringScalarObject PyBytesObject\r\n+#ifndef Py_LIMITED_API\r\n typedef struct {\r\n         /* note that the PyObject_HEAD macro lives right here */\r\n         PyUnicodeObject base;\r\n@@ -143,6 +144,7 @@ typedef struct {\r\n         char *buffer_fmt;\r\n     #endif\r\n } PyUnicodeScalarObject;\r\n+#endif\r\n\r\n```\r\n\r\nbut the build failed. I got [failure.txt](https://github.com/cython/cython/files/13820335/failure.txt)\r\n\r\nDid I do something wrong? I had these defines:\r\n```\r\n-DNPY_NO_DEPRECATED_API=0,\r\n-DNPY_TARGET_VERSION=NPY_2_0_API_VERSION,\r\n-DCPYTHON_LIMITED_API=1,\r\n-DPy_LIMITED_API=0x030700f0,\r\n```",
            "created_at": "2024-01-03T15:01:04Z",
            "html_url": "https://github.com/cython/cython/issues/5697#issuecomment-1875510655",
            "id": 1875510655,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/5697",
            "node_id": "IC_kwDOABDGAc5vygV_",
            "performed_via_github_app": null,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/cython/cython/issues/comments/1875510655/reactions"
            },
            "updated_at": "2024-01-03T15:01:04Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/1875510655",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/823911?v=4",
                "events_url": "https://api.github.com/users/mattip/events{/privacy}",
                "followers_url": "https://api.github.com/users/mattip/followers",
                "following_url": "https://api.github.com/users/mattip/following{/other_user}",
                "gists_url": "https://api.github.com/users/mattip/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mattip",
                "id": 823911,
                "login": "mattip",
                "node_id": "MDQ6VXNlcjgyMzkxMQ==",
                "organizations_url": "https://api.github.com/users/mattip/orgs",
                "received_events_url": "https://api.github.com/users/mattip/received_events",
                "repos_url": "https://api.github.com/users/mattip/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mattip/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mattip/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mattip"
            }
        }
    ],
    "comments": 6,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/5697/comments",
    "created_at": "2023-09-12T16:10:01Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": "70336c75fca2f4f1e31677bbc88bd94a91c74b96",
            "commit_url": "https://api.github.com/repos/da-woods/cython/commits/70336c75fca2f4f1e31677bbc88bd94a91c74b96",
            "created_at": "2023-09-12T21:08:24Z",
            "event": "referenced",
            "id": 10351671585,
            "node_id": "REFE_lADOABDGAc5w0mmqzwAAAAJpAfkh",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10351671585"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": "d693e91ed5ceb2a4443669b930ba01a480d61924",
            "commit_url": "https://api.github.com/repos/cython/cython/commits/d693e91ed5ceb2a4443669b930ba01a480d61924",
            "created_at": "2023-11-09T18:37:42Z",
            "event": "referenced",
            "id": 10916737921,
            "node_id": "REFE_lADOABDGAc5w0mmqzwAAAAKKsDOB",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/10916737921"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2023-11-19T21:51:41Z",
            "event": "labeled",
            "id": 11004681426,
            "label": {
                "color": "F5AB5D",
                "name": "limited api"
            },
            "node_id": "LE_lADOABDGAc5w0mmqzwAAAAKP7hzS",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/11004681426"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/10536947?v=4",
                "events_url": "https://api.github.com/users/da-woods/events{/privacy}",
                "followers_url": "https://api.github.com/users/da-woods/followers",
                "following_url": "https://api.github.com/users/da-woods/following{/other_user}",
                "gists_url": "https://api.github.com/users/da-woods/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/da-woods",
                "id": 10536947,
                "login": "da-woods",
                "node_id": "MDQ6VXNlcjEwNTM2OTQ3",
                "organizations_url": "https://api.github.com/users/da-woods/orgs",
                "received_events_url": "https://api.github.com/users/da-woods/received_events",
                "repos_url": "https://api.github.com/users/da-woods/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/da-woods/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/da-woods/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/da-woods"
            },
            "commit_id": "d039e1eab52b66cad224f1c61c142d843ac44b3f",
            "commit_url": "https://api.github.com/repos/da-woods/cython/commits/d039e1eab52b66cad224f1c61c142d843ac44b3f",
            "created_at": "2023-11-26T17:22:57Z",
            "event": "referenced",
            "id": 11063506174,
            "node_id": "REFE_lADOABDGAc5w0mmqzwAAAAKTb7T-",
            "performed_via_github_app": null,
            "url": "https://api.github.com/repos/cython/cython/issues/events/11063506174"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/5697/events",
    "html_url": "https://github.com/cython/cython/issues/5697",
    "id": 1892837802,
    "labels": [
        {
            "color": "F5AB5D",
            "default": false,
            "description": "",
            "id": 4210073287,
            "name": "limited api",
            "node_id": "LA_kwDOABDGAc768J7H",
            "url": "https://api.github.com/repos/cython/cython/labels/limited%20api"
        }
    ],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/5697/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "I_kwDOABDGAc5w0mmq",
    "number": 5697,
    "performed_via_github_app": null,
    "reactions": {
        "+1": 0,
        "-1": 0,
        "confused": 0,
        "eyes": 0,
        "heart": 0,
        "hooray": 0,
        "laugh": 0,
        "rocket": 0,
        "total_count": 0,
        "url": "https://api.github.com/repos/cython/cython/issues/5697/reactions"
    },
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "state_reason": null,
    "timeline_url": "https://api.github.com/repos/cython/cython/issues/5697/timeline",
    "title": "[BUG] Issue with cimport numpy when using CYTHON_LIMITED_API",
    "updated_at": "2024-01-03T15:01:05Z",
    "url": "https://api.github.com/repos/cython/cython/issues/5697",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/314716?v=4",
        "events_url": "https://api.github.com/users/astrofrog/events{/privacy}",
        "followers_url": "https://api.github.com/users/astrofrog/followers",
        "following_url": "https://api.github.com/users/astrofrog/following{/other_user}",
        "gists_url": "https://api.github.com/users/astrofrog/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/astrofrog",
        "id": 314716,
        "login": "astrofrog",
        "node_id": "MDQ6VXNlcjMxNDcxNg==",
        "organizations_url": "https://api.github.com/users/astrofrog/orgs",
        "received_events_url": "https://api.github.com/users/astrofrog/received_events",
        "repos_url": "https://api.github.com/users/astrofrog/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/astrofrog/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/astrofrog/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/astrofrog"
    }
}